[project]
version = "0.1.0"
description = "ECOD rust implementation."
authors = [
    {name = "nedeadinside",email = "aquvva67@gmail.com"}
]
name = "fast-ecod"
requires-python = ">=3.12,<3.15"
dependencies = [
    "numpy (>=1.26)"
]

[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "maturin (>=1.9,<2.0)",
    "ruff (>=0.16.0,<0.17.0)",
    "pytest (>=9.0)",
]

[tool.maturin]
python-source = "python"
module-name = "fast_ecod._core"

[tool.pytest.ini_options]
testpaths = ["tests"]
